### ISSUE TITLE
Make `name` optional in Materialize

### ISSUE THREAD

**Issue by xaviervia** [react-entanglement/react-entanglement#11]
Assuming the component to be materialized has a `name` or `displayName`, the `name` prop in `Materialize` can be dismissed. Of course, consumers not passing the `name` prop would have to make sure that the value is correct. This would be some nice sugar to simplify usage.

**Comment by pirelenito** [comment]
I would leave the `name` parameter still, specially since we are not using the constructor in the `Scatter` component. And I see a valid use-case where people use more complex names, like: `payment.methods.Card` as the name of the component.

Here I think that having a single way of doing it (explicit names), might be better.

**Comment by xaviervia** [comment]
Yes, yes, I'm not suggesting removing it, I'm suggesting leaving it as optional and make Materialize try to pick it up from `displayName` or `name` of the component if not provided.

**Comment by pirelenito** [comment]
Given the new API, I guess we can also reject this.
